### ISSUE TITLE
发送命令后报错，无法拿到cpu相关的值

### ISSUE THREAD

**Issue by Kaguya233qwq** [lgc-NB2Dev/nonebot-plugin-picstatus#22]
![QQ_Image_1681134426571](https://user-images.githubusercontent.com/53631287/230913674-5c8a9f92-13e9-4614-8163-647e298fcad8.jpg)
Arm64的ubuntu系统。请问小饼干佬，如图，什么情况下cpu_freq为空呢，如何解决呢

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/230921629-ccd8ce33-cb4a-4ddf-bc8b-7b1339854320.png)

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/230922191-e4e814de-85bc-4646-8cac-b54f966eb5f2.png)

**Comment by lgc2333** [comment]
不知道 很玄学

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/230922554-6f5939a7-5458-4388-bca7-a98fa1a46c65.png)

**Comment by Kaguya233qwq** [comment]
已收到，我会试试，蟹蟹~
