### ISSUE TITLE
获取运行状态图片失败，请检查后台输出

### ISSUE THREAD

**Issue by XiaoLong2333** [lgc-NB2Dev/nonebot-plugin-picstatus#23]
![图片](https://user-images.githubusercontent.com/42651551/233856720-e90e632c-5c03-4cfb-b1ed-58b9f9eb18e9.png)

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233858104-1ec68398-2967-4c30-8dab-184c69ec108e.png)

**Comment by XiaoLong2333** [comment]
上边启动是可以了，但还是出现
![图片](https://user-images.githubusercontent.com/42651551/233858387-c6e4e1ea-9569-4f24-a6e2-f5e617f2c8a2.png)

**Comment by lgc2333** [comment]
更新试试

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233925870-d1772db8-585c-4d24-a1cb-b6e300d519c5.png)
看了 一下是0.3.3

**Comment by XiaoLong2333** [comment]
请问一下更新代码啥来着

**Comment by XiaoLong2333** [comment]
更新以后还是0.3.3

**Comment by lgc2333** [comment]
是0.3.4，镜像源可能更新会慢

**Comment by XiaoLong2333** [comment]
现在有代理的话，正常源是更新地址是啥来着

**Comment by lgc2333** [comment]
可以换清华源尝试
https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

或者不用镜像源
`pip config unset global.index-url`

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233929309-7149cb90-f3dc-436b-b974-b68d4137e540.png)
![图片](https://user-images.githubusercontent.com/42651551/233929361-2c308e25-d80f-4795-8baa-1d9a0393b5e8.png)
添加代理以后还是报错

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233930234-0568f8ff-fae5-4d24-b73a-f8ea91fe87e8.png)

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233930759-b821a926-bef3-4791-97a7-f70b1c92f4b5.png)
已更新到0.3.4

**Comment by lgc2333** [comment]
你试试看还有没有问题

**Comment by XiaoLong2333** [comment]
https://user-images.githubusercontent.com/42651551/233929309-7149cb90-f3dc-436b-b974-b68d4137e540.png
https://user-images.githubusercontent.com/42651551/233929361-2c308e25-d80f-4795-8baa-1d9a0393b5e8.png

**Comment by XiaoLong2333** [comment]
![图片](https://user-images.githubusercontent.com/42651551/233936547-733198c4-03d3-47d0-96c2-a65b1d5e7d8d.png)
![图片](https://user-images.githubusercontent.com/42651551/233936578-56f1e003-d19e-4513-9e8c-30b5fdba4f91.png)
问题依旧

**Comment by lgc2333** [comment]
没更新成功吧，新版本这行代码在423行，你显示的是424

**Comment by lgc2333** [comment]
用 `nb plugin update picstatus` 试试看

**Comment by XiaoLong2333** [comment]
已解决，可以使用了
