### ISSUE TITLE
关于头像api获取的问题

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [lgc-NB2Dev/nonebot-plugin-picstatus#25]
希望可以弄一个配置项，获取bot头像的超时时间
用家宽挂的bot有时候会访问不了头像api，发送“状态”命令时如果获取不了头像，状态图则会延迟5-7分钟才会发送，希望可以配置获取头像图的超时时间

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/releases/tag/0.4.2
