### ISSUE TITLE
更新0.4.1后，Linux(armbian)在未配置PS_FONT的情况下中文乱码

### ISSUE THREAD

**Issue by YYY-919** [lgc-NB2Dev/nonebot-plugin-picstatus#27]
系统里是有中文字体的
不知道其他版本的Linux有没有这个问题
应该是0.4.1删除自带字体导致的，是不是因为插件太大了要删除自带字体
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/91111268/7ec069be-dd7a-4b8c-9336-ab2693c389ec)

这个是删除插件自带字体的前一个版本（0.4.0）
![20230630180514](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/91111268/078eaeff-4861-4798-bb9f-ebfd4a36a6e8)

还是希望插件能开箱即用（doge）

**Comment by lgc2333** [comment]
因为带上字体的话包体太大了，所以新版我选择了外置字体，你这种情况可能是字体缓存的问题，清一下就好了
https://github.com/MeetWq/pil-utils#%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93

**Comment by YYY-919** [comment]
OK，谢谢啦
