### ISSUE TITLE
字体无法显示

### ISSUE THREAD

**Issue by Sydrr0** [lgc-NB2Dev/nonebot-plugin-picstatus#28]
您好，我在安装了重新安装了字体后还是运行不了
安装并启用缓存命令（我已运行完毕）：
sudo apt install fonts-noto-cjk fonts-noto-color-emoji
sudo locale-gen zh_CN zh_CN.UTF-8
sudo update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
fc-cache -fv
系统：linux sever 22.04
插件为最新版，用商店指令安装

**Comment by lgc2333** [comment]
https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/59048777/5be468ca-c882-47c4-92ed-1b6499d3c527)

**Comment by Sydrr0** [comment]
> https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85
> 
> ![image](https://user-images.githubusercontent.com/59048777/257053657-5be468ca-c882-47c4-92ed-1b6499d3c527.png)

您好，冒昧的打扰您，我并没有发现这个文件夹

**Comment by lgc2333** [comment]
您好，这边的路径以 `~` 开头 ，请您不要忽略了，关于 `~` 开头的路径是什么意思，请您自己上网搜索一下呢亲亲

**Comment by Sydrr0** [comment]
> 您好，这边的路径以 `~` 开头 ，请您不要忽略了，关于 `~` 开头的路径是什么意思，请您自己上网搜索一下呢亲亲

好的，打扰您了
