### ISSUE TITLE
获取运行状态图失败，UnboundLocalError: local variable 'percentswap' referenced before assignment

### ISSUE THREAD

**Issue by Baimotong** [lgc-NB2Dev/nonebot-plugin-picstatus#31]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/30062345/3aeeaa76-bc9e-4ae0-815d-675efe83017e)
如图所示，求助

**Comment by lgc2333** [comment]
上游库问题

**Comment by lgc2333** [comment]
哦，这里的问题应该已经被我的PR修复了，试试 `pip install -U psutil`

**Comment by Baimotong** [comment]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/30062345/c374a9a2-765e-402c-a2f4-1646fd3e3fbe)
还是不行

**Comment by lgc2333** [comment]
好吧，看来他们还没发版，你自己按照我pr里的更改手动改一下吧

**Comment by Baimotong** [comment]
可以用了，感谢！
