### ISSUE TITLE
linux上提示权限问题PermissionErro

### ISSUE THREAD

**Issue by huangzhitian** [lgc-NB2Dev/nonebot-plugin-picstatus#32]
PermissionError: [Errno 13] Permission denied: '/proc/filesystems'

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/129321746/ecda0f17-6b9d-4905-bd60-1bba03cc6239)

**Comment by PackageInstaller** [comment]
看了一下涉及报错的语句，应该和虚拟环境中psutil中_pslinux.py的第**1268**行

`with open_text("%s/filesystems" % procfs_path) as f:`

这句有关？

然而我在我的Arch linux发行版上没有这个问题，就很玄学🤔

**Comment by huangzhitian** [comment]
> 看了一下涉及报错的语句，应该和虚拟环境 **psutil** 包中 **_pslinux.py** 的第 **1268** 行
> 
> `with open_text("%s/filesystems" % procfs_path) as f:`
> 
> 这句有关？
> 
> 然而我在我的Arch linux发行版上没有这个问题，就很玄学🤔
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/129321746/1451ef0e-e283-4245-9cb1-07af0b102bd2)
这里吗

**Comment by PackageInstaller** [comment]
> > 🤔你这 Bot 运行在什么系统上的，这是没权限读文件啊
> 
> 手机虚拟机 debian上

那弹权限问题也不奇怪了

**Comment by PackageInstaller** [comment]
是不是termux中装了debian这种

**Comment by huangzhitian** [comment]
> 是不是termux中装了debian这种

aidlux，自带的debian

**Comment by XieXiLin2** [comment]
不推荐在这类 Android 虚拟机使用，如有必要请使用完全隔离的虚拟机或使用 root 权限运行。
