### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by BalconyJH** [lgc-NB2Dev/nonebot-plugin-picstatus#33]
# 环境
- 操作系统 winserver2019
- Python 版本 3.9.13

# 问题描述
当系统存在一个类似
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/73932916/c949c29a-8a6b-4265-b743-4510e0bd837a)
的设备（我也不知道哪来的），get_one()捕捉到后会返回DiskUsageWithExc被draw_disk_usage()当字符串渲染，效果如下
![666d4d934181da4a9c269f3dd5bec840](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/73932916/4d98b281-a4a4-4205-881c-6b4159b6e3a5)

# 期望的结果
不渲染该驱动器

# 截图或日志
![{BC0690C3-04AB-48bb-A8AA-DC692ADA239F}](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/73932916/4f2dccfc-f03c-40d0-bdc6-52b9f23f193c)

# 可能的解决方案
在nonebot_plugin_picstatus/status.py第199行添加`except PermissionError:
            logger.error(f"读取 {mountpoint} 时没有足够的权限或设备未就绪")
            return None`
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/73932916/70a625f9-3b49-4719-a815-12fe502f4caf)

**Comment by lgc2333** [comment]
这是非预期行为，正常应该只显示报错内容
