### ISSUE TITLE
添加对 nonebot-adapter-dodo 适配器的支持

### ISSUE THREAD

**Issue by Ghost-chu** [lgc-NB2Dev/nonebot-plugin-picstatus#35]
```
nonebot_plugin_picstatus | SAA 不支持的平台，取消响应
```

https://github.com/nonebot/adapter-dodo

**Comment by XieXiLin2** [comment]
上游库尚未支持，请先向 [nonebot-plugin-send-anything-anywhere](https://github.com/MountainDash/nonebot-plugin-send-anything-anywhere) 提出适配申请。

**Comment by felinae98** [comment]
(有兴趣在 SAA 协助支持 DoDo 吗

**Comment by XieXiLin2** [comment]
saa 发版了，更新一下 saa 后再试试能不能用。
