### ISSUE TITLE
feature: 支持插件自统计消息量

### ISSUE THREAD

**Issue by HuaWaterED** [lgc-NB2Dev/nonebot-plugin-picstatus#42]
就是，如果接了别的框架，比如云崽，koishi等，bot发送的消息就没办法统计上，如果打开onebot v11的自发消息上报依旧没办法统计上，请问可以支持这个功能吗？

**Comment by lgc2333** [comment]
可以做一个配置项 `PS_USE_MESSAGE_SENT_EVENT`
