### ISSUE TITLE
Bug(?

### ISSUE THREAD

**Issue by HuaWaterED** [lgc-NB2Dev/nonebot-plugin-picstatus#43]
更新到2.0后出现无法加载的问题，已经尝试过重装整个环境和不写ps相关的任何配置(使它保持默认)

报错相关信息:
Decorators defined with incorrect fields: nonebot_plugin_picstatus.templates.default.TemplateConfig:31221280.resolve_css_url (use check_fields=False if you're inheriting from the model and intended this)

![Screenshot_2024-03-17-22-15-34-852_com termux](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/116249117/de3b7883-dc16-4739-a3db-e1dbc05ab285)

**Comment by XieXiLin2** [comment]
nonebot_plugin_picstatus/templates/default/__init__.py#L37-L39

**Comment by HuaWaterED** [comment]
我对比了37-39行，似乎我本地下载的和github上的是一样的
请问我该怎么做？

**Comment by lgc2333** [comment]
我的锅
