### ISSUE TITLE
调用此插件后无法用sys.exit关闭窗口

### ISSUE THREAD

**Issue by MoonofBridge24** [lgc-NB2Dev/nonebot-plugin-picstatus#44]
windows部署的，在调用一次此插件后无法使用sys.exit正常关闭窗口，窗口本身不再接收新的事件但是就是不关闭，貌似有什么东西阻塞了(？gpt告诉我的)，虽然可以用os.kill强制关闭，但是还是希望能正常exit吧

**Comment by lgc2333** [comment]
上游依赖 [htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender/) 的问题，请去那边开issue

**Comment by MoonofBridge24** [comment]
好的，但是能不能告知一下大概如何描述此bug？我没有仔细看过代码，去那边提issue的时候不太清楚如何准确的描述，非常感谢
