### ISSUE TITLE
图片背景图来源可否增加自定义链接

### ISSUE THREAD

**Issue by RSJWY** [lgc-NB2Dev/nonebot-plugin-picstatus#48]
如题
我想自行编写一个图片API，来返回背景图

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/releases/tag/v2.1.0
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/tree/master/examples/external_example
