### ISSUE TITLE
获取背景图片时报错

### ISSUE THREAD

**Issue by WuSheng125** [lgc-NB2Dev/nonebot-plugin-picstatus#49]
日志如下：
![QQ20240828-225255](https://github.com/user-attachments/assets/805ccc30-3be2-4243-9fd2-33f348328995)
相关配置文件：
’‘’
PS_COMMAND=["运行状态", "status"]
PS_ONLY_SU=true
PS_REPLY_TARGET=false
PS_DISCONNECT_RESET_COUNTER=false
PS_DEFAULT_COMPONENTS=["header", "cpu_mem", "disk", "network", "footer"]
PS_BG_PROVIDER=loli
‘’‘
相关软件版本：
NoneBot v2.3.3
PicStatus v2.1.1
Python 3.9
Debian 11

**Comment by WuSheng125** [comment]
是的

**Comment by lgc2333** [comment]
了解了，初步推断此错误是`driver.on_startup`时使用的event loop与处理消息时不同

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/releases/tag/v2.1.2

可以尝试一下
