### ISSUE TITLE
安装插件自动下载依赖时，关于 httpx 版本>=0.28 的问题

### ISSUE THREAD

**Issue by Azrael070** [lgc-NB2Dev/nonebot-plugin-picstatus#55]
2.1.3 说兼容了 httpx 0.28，但下载依赖时依旧会因为有部分依赖要求 httpx 小于 0.24 而安装失败
![93bbef6cc5250fa963baf03b3398db8a](https://github.com/user-attachments/assets/cb896f77-b9d0-4a7e-b0a3-842b77ff4d44)

**Comment by lgc2333** [comment]
其他插件的锅，我不背

**Comment by lgc2333** [comment]
但是你提醒了我目前最新稳定版的nonebot2的httpx适配器还没适配httpx0.28，刚改了一下依赖要求
